# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: At-Bristol Developers
email: seamus.foley@at-bristol.org.uk
description: > # this means to ignore newlines until "baseurl:"
  At-Bristol Developers
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://at-bristol.org.uk" # the base hostname & protocol for your site
twitter_username: AtBristol
github_username:  At-Bristol

# Build settings
markdown: kramdown
